version: "3.8"

services:
  monodevelop:
    image: zachdeibert/monodevelop
    container_name: monodevelop
    hostname: monodevelop
    network_mode: "host"
    working_dir: /home/${USER}
    entrypoint: /bin/bash
    command: >
      -c "
      echo Starting monodevelop from docker;
      if ! getent group ${GROUP_ID} > /dev/null; then groupadd -g ${GROUP_ID} ${USER}; fi;
      useradd -r -d /home/${USER} -s /bin/bash -g $(id -gn) -G sudo -u ${USER_ID} ${USER};
      su -c '/launch.sh ${DISPLAY}' ${USER}"
    environment:
      - DISPLAY=:0
    volumes:
      - .:/home/${USER}
      - /tmp:/tmp
      - ${XAUTHORITY}:/root/.Xauthority
    stdin_open: true
    tty: true

  coppelia-sim:
    image: brgsil/ws3d-coppelia
    container_name: coppelia-sim
    network_mode: "host"
    privileged: true
    devices:
      - "/dev/snd"
    environment:
      - DISPLAY=:0
    volumes:
      - ${XAUTHORITY}:/root/.Xauthority
    ports:
      - "4011:4011"
    tty: true
